import pyautogui


# pyautogui.sleep(3)
# pyautogui.press('winleft')
# pyautogui.sleep(1)
# pyautogui.write('\\\\172.16.0.4\chaves')
# pyautogui.sleep(1)
# pyautogui.press('enter')
#
# pyautogui.sleep(3)
# pyautogui.write('dto')
# pyautogui.write('2022')
# pyautogui.sleep(1)
# pyautogui.press(['tab', 'tab'])
# pyautogui.press('enter')


pyautogui.alert('***Atenção***\n'
                'Clique em [ok] para inicializar o programa.')
pyautogui.press('winleft')
pyautogui.sleep(3)
pyautogui.write('C:')
pyautogui.sleep(3)
pyautogui.press('enter')


pyautogui.sleep(3)
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(3)
pyautogui.write('PV 59117')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.press('tab')
pyautogui.sleep(3)
pyautogui.press('space')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(3)

pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(3)
pyautogui.write('CHAVES')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.press('tab')
pyautogui.sleep(3)
pyautogui.press('space')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.keyDown('shift')
pyautogui.press('right', presses=29)
pyautogui.keyUp('shift')
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(3)
pyautogui.press('backspace')
pyautogui.sleep(3)
pyautogui.press('down')
pyautogui.sleep(3)

pyautogui.press('backspace', presses=2)
pyautogui.sleep(3)
pyautogui.hotkey('ctrl', 's')
pyautogui.sleep(3)
pyautogui.hotkey('alt','tab')

pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(3)
pyautogui.write('PV 5555')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(2)
pyautogui.press('space')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(3)
pyautogui.write('ATIVADAS')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('up')


pyautogui.sleep(3)
pyautogui.hotkey('ctrl', 'V')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 's')

pyautogui.sleep(3)

pyautogui.press('win')
pyautogui.sleep(3)
pyautogui.write('wmic')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(3)
pyautogui.write('bios get serialnumber')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'f')
pyautogui.sleep(1)
pyautogui.write('SerialNumber')
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('esc')
pyautogui.sleep(2)
pyautogui.hotkey('ctrl','shift','down','right')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl','c')
pyautogui.sleep(2)
pyautogui.hotkey('alt','tab')
pyautogui.sleep(2)
pyautogui.press('backspace')
pyautogui.sleep(1)
pyautogui.press('space')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'v')
pyautogui.sleep(1)
pyautogui.press('up',  presses=2)
pyautogui.sleep(1)
pyautogui.keyDown('shift')
pyautogui.press('right', presses=29)
pyautogui.keyUp('shift')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(1)

pyautogui.press('winleft')
pyautogui.sleep(3)
pyautogui.write('slui')
pyautogui.sleep(1)
pyautogui.press('right')
pyautogui.press('down')
pyautogui.sleep(3)
pyautogui.press('enter')
pyautogui.sleep(5)
pyautogui.press('enter')
pyautogui.sleep(5)
pyautogui.alert('***Atenção***\n'
                'COLE A CHAVE DO PRODUTO PARA A ATIVAÇÃO!!! '
                       '(ctrl + v) E CLICK EM [AVANÇAR] >>>')





